site_name: Portfolio
site_author: Krzysztof Kleszcz
site_description: >-
  Portfolio moich projektów. Ciesze sięę...

repo_name: krzysztofkleszcz50/datascience_portfolio
repo_url: https://github.com/krzysztofkleszcz50/datascience_portfolio


theme:
  name: material
  palette:
    primary: amber

nav:
- Strona Domowa: index.md
- Obecne projekty: 
  - "Titanic": titanic/index.md
- Poprzednie projekty:
  - "Iris": iris/index.md

